#Note: Do not edit this file, it is managed by an editor script using the data in`/Networking/network_objects.json`.
extends Node

## 
## [b]Object id:[/b] 0
## [b]Scenes:[/b] one shared by both peers
## [codeblock]
## scene  res://main.tscn
## [/codeblock]
var TEST_PLAYER: String = "TEST_PLAYER"
